---
- name: install npm
  yum: name=npm state=present
  tags:
    - nodejs
    - packages

- name: install bower
  npm: name=bower version={{ nodejs_bower_version }} global=yes state=present
  when: nodejs_install_bower
  tags:
    - nodejs
    - bower
    - packages

- name: install gulp
  npm: name=gulp version={{ nodejs_gulp_version }} global=yes state=present
  when: nodejs_install_gulp
  tags:
    - nodejs
    - gulp
    - packages

- name: install grunt-cli
  npm: name=grunt-cli version={{ nodejs_grunt_cli_version }} global=yes state=present
  when: nodejs_install_grunt_cli
  tags:
    - nodejs
    - grunt
    - grunt-cli
    - packages
