---
- name: install nodesource key
  rpm_key:
    key: https://rpm.nodesource.com/pub/el/NODESOURCE-GPG-SIGNING-KEY-EL
    state: present
  tags:
    - nodejs
    - packages
    - repos

- name: install nodesource repo
  yum_repository:
    name: nodesource
    description: Node.js Packages for Enterprise Linux
    baseurl: "https://rpm.nodesource.com/pub_{{ nodejs_version }}.x/el/{{ ansible_distribution_major_version }}/$basearch"
    failovermethod: priority
    enabled: yes
    gpgcheck: yes
    priority: 1
  tags:
    - nodejs
    - packages
    - repos

- name: install nodesource source repo
  yum_repository:
    name: nodesource-src
    description: Node.js Source Packages for Enterprise Linux
    baseurl: "https://rpm.nodesource.com/pub_{{ nodejs_version }}.x/el/{{ ansible_distribution_major_version }}/SRPMS"
    failovermethod: priority
    enabled: no
    gpgcheck: yes
    priority: 1
  tags:
    - nodejs
    - packages
    - repos

- name: install nodejs
  yum:
    name: nodejs
    state: present
  tags:
    - nodejs
    - packages

- name: install bower
  npm: name=bower version={{ nodejs_bower_version }} global=yes state=present
  when: nodejs_install_bower
  tags:
    - nodejs
    - bower
    - packages

- name: install gulp
  npm: name=gulp version={{ nodejs_gulp_version }} global=yes state=present
  when: nodejs_install_gulp
  tags:
    - nodejs
    - gulp
    - packages

- name: install grunt-cli
  npm: name=grunt-cli version={{ nodejs_grunt_cli_version }} global=yes state=present
  when: nodejs_install_grunt_cli
  tags:
    - nodejs
    - grunt
    - grunt-cli
    - packages
